name: Daily car workflow

on:
  schedule:
    # Send the newsletter daily at 7:15 am.
    # If your not familiar with cron, this can ease the configuration https://crontab.guru/#15_7_*_*_* 
    - cron: '0 0 * * *'
  # This allows you to manually run the workflow in the repository's "Actions" tab.
  workflow_dispatch:

jobs:
  Query-And-Notification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-dotenv
      - name: Update the local list of cars
        env:
          API: ${{ secrets.AutoDevAPI}}
        run: |
          python daily_newsletter.py